workflows:
  android-workflow:
    name: Android Workflow
    instance_type: linux
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        CODE_MAGIC_URL: https://codemagic.io/applications
    cache:
      cache_paths:
        - ~/.pub-cache
    scripts:
      - name: Set up environment
        script: |
          flutter doctor -v
          flutter --version

      - name: Install dependencies
        script: |
          flutter pub get

      - name: Build APK (Android only)
        script: |
          flutter build apk --release --debug-prints

    artifacts:
      - build/app/outputs/flutter-apk/*.apk

    publishing:
      email:
        recipients:
          - your-email@example.com
