workflows:
  default-workflow:
    name: Default Workflow
    instance_type: linux
    max_build_duration: 60
    environment:
      flutter: stable
    cache:
      cache_paths:
        - ~/.pub-cache
    scripts:
      - name: Build APK
        script: |
          flutter pub get
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
